### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jagroop** [nunomaduro/laravel-zero#15]
when i run this command
```shell
php application build zonda
```

getting below fatal error

#### system config 
- PHP 7.0
- OS Ubuntu
- Webserver : APACHE 2

```
PHP Fatal error:  Uncaught TypeError: Return value of App\Console\Commands\Build::configure() must be an instance of App\Console\Commands\void, none returned in /var/www/html/dev/zero/app/Console/Commands/Build.php:57
Stack trace:
#0 /var/www/html/dev/zero/vendor/symfony/console/Command/Command.php(63): App\Console\Commands\Build->configure()
#1 /var/www/html/dev/zero/vendor/illuminate/console/Command.php(124): Symfony\Component\Console\Command\Command->__construct('build')
#2 /var/www/html/dev/zero/vendor/illuminate/console/Command.php(98): Illuminate\Console\Command->configureUsingFluentDefinition()
#3 /var/www/html/dev/zero/app/Console/Application.php(86): Illuminate\Console\Command->__construct()
#4 /var/www/html/dev/zero/app/Console/Application.php(69): App\Console\Application->registerBaseCommands()
#5 /var/www/html/dev/zero/bootstrap/app.php(20): App\Console\Application->__construct(Object(Illuminate\Container\Container), Object(Illuminate\Events\Dispatcher))
#6 /var/www/html/dev/zero/bootstrap/init.php(17): require_onc in /var/www/html/dev/zero/app/Console/Commands/Build.php on line 57
```

**Comment by jagroop** [comment]
:man_facepalming: PHP 7.1 !!
sorry for the false alarm :unamused:
