### ISSUE TITLE
composer create fails at post-install

### ISSUE THREAD

**Issue by StyxOfDynamite** [nunomaduro/laravel-zero#5]
```
▶ composer create-project --prefer-dist nunomaduro/laravel-zero swear-word-scraper
Installing nunomaduro/laravel-zero (v1.1.3)
  - Installing nunomaduro/laravel-zero (v1.1.3): Downloading (failed)       
The "https://api.github.com/repos/nunomaduro/laravel-zero/zipball/f115ab5e46a7971f2dbcc30847a974b7fd2a6fae" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
Downloading (100%)         
Created project in swear-word-scraper
Loading composer repositories with package information

The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
Updating dependencies (including require-dev)
Package operations: 42 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.3.2): Downloading (failed)       
Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.3.0): Loading from cache
  - Installing symfony/console (v3.3.2): Downloading (failed)       
Downloading (100%)         
  - Installing symfony/translation (v3.3.2): Downloading (failed)       
Downloading (100%)         
  - Installing nesbot/carbon (1.22.1): Loading from cache
  - Installing paragonie/random_compat (v2.0.10): Loading from cache
  - Installing illuminate/contracts (v5.4.19): Loading from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing illuminate/support (v5.4.19): Downloading (failed)       
Downloading (100%)         
  - Installing illuminate/console (v5.4.19): Downloading (failed)       
Downloading (100%)         
  - Installing illuminate/container (v5.4.19): Loading from cache
  - Installing illuminate/events (v5.4.19): Downloading (failed)       
Downloading (100%)         
  - Installing illuminate/config (v5.4.19): Downloading (100%)         
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)         
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)         
  - Installing sebastian/object-enumerator (3.0.2): Downloading (failed)       
Downloading (100%)         
  - Installing sebastian/global-state (2.0.0): Downloading (failed)       
Downloading (100%)         
  - Installing sebastian/exporter (3.1.0): Downloading (failed)       
Downloading (100%)         
  - Installing sebastian/environment (3.0.3): Downloading (failed)       
Downloading (100%)         
  - Installing sebastian/diff (1.4.3): Downloading (100%)         
  - Installing sebastian/comparator (2.0.0): Downloading (100%)         
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (4.0.1): Downloading (failed)       
Downloading (100%)         
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Downloading (failed)       
Downloading (100%)         
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (1.4.11): Loading from cache
  - Installing phpunit/php-code-coverage (5.2.1): Downloading (100%)         
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.2.1): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.1.1): Loading from cache
  - Installing phpspec/prophecy (v1.7.0): Loading from cache
  - Installing phar-io/version (1.0.1): Downloading (100%)         
  - Installing phar-io/manifest (1.0.1): Downloading (failed)       
Downloading (failed)       
Downloading (failed)    Failed to download phar-io/manifest from dist: The "https://api.github.com/repos/phar-io/manifest/zipball/2df402786ab5368a0169091f61a7c1e0eb6852d0" file could not be downloaded: failed to open stream: Operation timed out
    Now trying to download from source
  - Installing phar-io/manifest (1.0.1): Cloning 2df402786a
  - Installing myclabs/deep-copy (1.6.1): Downloading (100%)         
  - Installing phpunit/phpunit (6.2.1): Downloading (failed)       
Downloading (100%)         
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/filesystem ()
symfony/console suggests installing symfony/process ()
symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
illuminate/support suggests installing illuminate/filesystem (Required to use the composer class (5.2.*).)
illuminate/support suggests installing symfony/process (Required to use the composer class (~3.2).)
illuminate/support suggests installing symfony/var-dumper (Required to use the dd function (~3.2).)
illuminate/console suggests installing guzzlehttp/guzzle (Required to use the ping methods on schedules (~6.0).)
illuminate/console suggests installing mtdowling/cron-expression (Required to use scheduling component (~1.0).)
illuminate/console suggests installing symfony/process (Required to use scheduling component (~3.2).)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.3)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating autoload files
> php application install
PHP Fatal error:  Uncaught TypeError: Return value of App\Console\Commands\Build::configure() must be an instance of App\Console\Commands\void, none returned in /private/var/www/swear-word-scraper/app/Console/Commands/Build.php:57
Stack trace:
#0 /private/var/www/swear-word-scraper/vendor/symfony/console/Command/Command.php(63): App\Console\Commands\Build->configure()
#1 /private/var/www/swear-word-scraper/vendor/illuminate/console/Command.php(124): Symfony\Component\Console\Command\Command->__construct('build')
#2 /private/var/www/swear-word-scraper/vendor/illuminate/console/Command.php(98): Illuminate\Console\Command->configureUsingFluentDefinition()
#3 /private/var/www/swear-word-scraper/app/Console/Application.php(86): Illuminate\Console\Command->__construct()
#4 /private/var/www/swear-word-scraper/app/Console/Application.php(69): App\Console\Application->registerBaseCommands()
#5 /private/var/www/swear-word-scraper/bootstrap/app.php(20): App\Console\Application->__construct(Object(Illuminate\Container\Container), Object(I in /private/var/www/swear-word-scraper/app/Console/Commands/Build.php on line 57

Fatal error: Uncaught TypeError: Return value of App\Console\Commands\Build::configure() must be an instance of App\Console\Commands\void, none returned in /private/var/www/swear-word-scraper/app/Console/Commands/Build.php:57
Stack trace:
#0 /private/var/www/swear-word-scraper/vendor/symfony/console/Command/Command.php(63): App\Console\Commands\Build->configure()
#1 /private/var/www/swear-word-scraper/vendor/illuminate/console/Command.php(124): Symfony\Component\Console\Command\Command->__construct('build')
#2 /private/var/www/swear-word-scraper/vendor/illuminate/console/Command.php(98): Illuminate\Console\Command->configureUsingFluentDefinition()
#3 /private/var/www/swear-word-scraper/app/Console/Application.php(86): Illuminate\Console\Command->__construct()
#4 /private/var/www/swear-word-scraper/app/Console/Application.php(69): App\Console\Application->registerBaseCommands()
#5 /private/var/www/swear-word-scraper/bootstrap/app.php(20): App\Console\Application->__construct(Object(Illuminate\Container\Container), Object(I in /private/var/www/swear-word-scraper/app/Console/Commands/Build.php on line 57
Script php application install handling the post-create-project-cmd event returned with error code 255
```

**Comment by nunomaduro** [comment]
@StyxOfDynamite Checking the issue. What is the php version that you are using?

**Comment by StyxOfDynamite** [comment]
Opps. Sorry

```
▶ php -v
PHP 7.0.19 (cli) (built: May 21 2017 11:55:00) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by StyxOfDynamite** [comment]
Missed the requirement for PHP >= 7.1. Apologies for the interuption.
